---

- name: include distribution specific settings
  include_vars: file=ubuntu.yml

- name: setup php
  include: php.yml

- name: setup composer
  include: composer.yml

- name: setup fpm
  include: fpm.yml

- name: setup fpm pools
  include: fpm-pools.yml

- name: setup php-fpm supervisor service
  include: supervisor.yml
  when: swinxy.container == true