---

- name: install php-cli
  package:
    name: "{{ php.package_map['cli'] }}"

- name: install php extensions
  package:
    name: "{{ php.extension_package_map[item] }}"
    state: present
  with_items: "{{ php.extensions }}"